/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright (c) 2026, The SourceTracker3 Development Team */

/*
 * SourceTracker3 C ABI.
 *
 * This header refers to the Arrow C Data Interface structs -- ArrowArray,
 * ArrowSchema, and ArrowArrayStream -- by pointer only and deliberately does
 * not declare them. Declare them before including this header, e.g. by
 * including Arrow's abi.h or any header that defines the same struct names.
 *
 * The committed copy lives at crates/st3-capi/include/st3.h; `make header`
 * refreshes it, and the test gate fails if it drifts from the generated one.
 */

#ifndef ST3_H
#define ST3_H

/* Generated by cbindgen from st3-capi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// The only configuration layout version understood by this ABI. Callers set
// the `St3Config.struct_version` field to this value.
#define ST3_CONFIG_V1 1

// Result status of a C ABI call. `Ok` is zero; every failure is nonzero.
//
// The discriminants are ABI-stable: new variants are appended, never reordered.
typedef enum St3Status {
  // The call succeeded.
  ST3_STATUS_OK = 0,
  // An input was malformed: an invalid configuration, a null or misaligned
  // pointer, a bad Arrow schema/type/null, an unknown role, an out-of-range
  // index, or any other core validation failure. The specifics are in the
  // last-error string.
  ST3_STATUS_ERR_INVALID_INPUT,
  // Reserved. A sample was too shallow to analyze. The core currently keeps
  // and flags shallow samples rather than erroring, so this is defined for
  // ABI stability but not yet produced.
  ST3_STATUS_ERR_SHALLOW_SAMPLE,
  // No sample was labeled as a source.
  ST3_STATUS_ERR_NO_SOURCES,
  // Reserved. An allocation failed. Rust aborts on allocation failure rather
  // than returning, so this is defined for ABI stability but not yet produced.
  ST3_STATUS_ERR_OOM,
  // A panic was caught at the boundary (a library bug). See the last-error
  // string for the panic message.
  ST3_STATUS_ERR_PANIC,
} St3Status;

// How source samples are aggregated per environment. Named constants for the
// `St3Config.collapse` field.
typedef enum St3Collapse {
  // Per-taxon mean over the environment's source samples (floored to integer
  // counts). The default.
  ST3_COLLAPSE_MEAN = 0,
  // Per-taxon sum over the environment's source samples.
  ST3_COLLAPSE_SUM = 1,
} St3Collapse;

// Which per-sink estimator to run. Named constant for the
// `St3Config.estimator` field. Only the collapsed-Gibbs sampler ships in v1.
typedef enum St3EstimatorKind {
  // The collapsed-Gibbs source-attribution sampler.
  ST3_ESTIMATOR_KIND_GIBBS_COLLAPSED = 0,
} St3EstimatorKind;

// Opaque handle to a completed run's mixing results.
//
// Created by `st3_run` and destroyed by `st3_result_free`.
typedef struct St3Result St3Result;

// Opaque handle to an imported count table and its sample context.
//
// Created by `st3_table_from_arrow` and destroyed by `st3_table_free`. It is
// only ever passed by pointer.
typedef struct St3Table St3Table;

// Versioned run configuration passed to `st3_run`.
//
// The layout is frozen for a given `struct_version`; new fields are only ever
// appended under a higher version. `collapse` and `estimator` each hold a
// `St3Collapse` / `St3EstimatorKind` value (as an `int32_t`); the boolean flags
// are `uint8_t` (0 = false, nonzero = true). A rarefaction depth of `0`
// disables rarefaction for that role.
typedef struct St3Config {
  // ABI layout version; must equal `ST3_CONFIG_V1`.
  uint32_t struct_version;
  // `size_of` the config struct; must equal the library's own size.
  uint32_t struct_size;
  // Run seed. Output is a function of the seed alone, not the job count.
  uint64_t seed;
  // Worker count: `0` uses all logical cores, `1` runs serially, `n` uses `n`.
  int32_t jobs;
  // Target depth for source samples; `0` disables source rarefaction.
  int32_t source_rarefaction_depth;
  // Target depth for sink samples; `0` disables sink rarefaction.
  int32_t sink_rarefaction_depth;
  // Rarefy with replacement (multinomial) rather than without (reservoir).
  // `0` = false, nonzero = true.
  uint8_t with_replacement;
  // Collapse method: an `St3Collapse` value.
  int32_t collapse;
  // Run leave-one-out source prediction rather than sink prediction.
  // `0` = false, nonzero = true.
  uint8_t loo;
  // Emit the per-sink source × taxon assignment tally. `0` = false, nonzero =
  // true.
  uint8_t contingency;
  // Estimator kind: an `St3EstimatorKind` value.
  int32_t estimator;
  // Dirichlet prior count per feature in the source environments.
  double alpha1;
  // Dirichlet prior count per feature in the Unknown environment.
  double alpha2;
  // Prior count of sink sequences in each environment.
  double beta;
  // Independent Markov chains grown per sink.
  uint32_t restarts;
  // Retained draws per restart.
  uint32_t draws_per_restart;
  // Passes made before the first retained draw.
  uint32_t burnin;
  // Passes between retained draws (thinning gap).
  uint32_t delay;
} St3Config;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the SourceTracker3 C ABI version.
//
// The version is bumped only on a breaking change to the ABI (struct layout,
// enum discriminants, or function signatures); additive changes keep it stable.
// It currently returns `0` (the v1 surface has not shipped a breaking change).
// Returns a compile-time constant and so needs no unwind guard.
uint32_t st3_abi_version(void);

// Import a COO count table, feature ids, and per-sample metadata into a table
// handle, over the Arrow C Data Interface.
//
// Each input is a borrowed `(ArrowArray, ArrowSchema)` pair: `coo` is a struct
// array with `row` (feature index), `col` (sample index), and `val` (count)
// children; `feature_ids` is a string array in feature order; and `metadata` is
// a struct array with `sample_id`, `role` (`"source"`/`"sink"`), and `env`
// (nullable) columns in sample order. On success a new handle is
// written to `*out` and must later be freed with `st3_table_free`. On failure
// `*out` is set to null and the reason is available from `st3_last_error`.
//
// # Safety
// Every non-null array/schema pointer must reference a valid C Data Interface
// structure, and `out` must be a valid, writable `*mut *mut St3Table`. When all
// pointers are valid, each of the three arrays is *consumed* (the library
// releases it); the caller must relinquish them and not release them again.
enum St3Status st3_table_from_arrow(const ArrowArray *coo,
                                    const ArrowSchema *coo_schema,
                                    const ArrowArray *feature_ids,
                                    const ArrowSchema *feature_ids_schema,
                                    const ArrowArray *metadata,
                                    const ArrowSchema *metadata_schema,
                                    struct St3Table **out);

// Run source attribution over an imported table, producing a result handle.
//
// `table` is a handle from `st3_table_from_arrow`; `config` is a versioned
// `St3Config`. With `config.loo` set the run performs leave-one-out source
// prediction, otherwise sink prediction; rarefaction is applied first when a
// depth is configured. On success a new result handle is written to `*out` and
// must later be freed with `st3_result_free`. On failure `*out` is set to null
// and the reason is available from `st3_last_error`.
//
// # Safety
// `table` must be a live handle from `st3_table_from_arrow`, `config` a valid
// pointer to an initialized `St3Config`, and `out` a valid, writable
// `*mut *mut St3Result`.
enum St3Status st3_run(const struct St3Table *table,
                       const struct St3Config *config,
                       struct St3Result **out);

// Export a result's mixing **means** as a dense Arrow record batch.
//
// Writes an `(ArrowArray, ArrowSchema)` pair — a `sink_id` column plus one
// `Float64` column per environment (`Unknown` last), one row per sink — into the
// caller-provided slots. On success the caller owns and must release both.
//
// # Safety
// `result` must be a live handle from `st3_run`; `out` and `out_schema` must
// be valid, writable, aligned pointers to uninitialized FFI slots.
enum St3Status st3_result_means(const struct St3Result *result,
                                ArrowArray *out,
                                ArrowSchema *out_schema);

// Export a result's mixing **standard deviations** as a dense Arrow record
// batch, same shape as `st3_result_means`.
//
// The values are the per-draw standard deviations, never the Python
// reference's `×N_draws` quantity.
//
// # Safety
// As `st3_result_means`.
enum St3Status st3_result_stds(const struct St3Result *result,
                               ArrowArray *out,
                               ArrowSchema *out_schema);

// Export a result's per-sink source × taxon assignment tally as an Arrow array
// stream.
//
// Yields one flat-COO record batch per sink over the schema
// `[sink, source, feature, value]`. Requires the run to have been
// configured with `contingency = true`; otherwise returns
// `ST3_STATUS_ERR_INVALID_INPUT`. On success the caller owns the stream and must
// release it.
//
// # Safety
// `result` must be a live handle from `st3_run`; `out_stream` must be a valid,
// writable, aligned pointer to an uninitialized `FFI_ArrowArrayStream` slot.
enum St3Status st3_result_contingency_stream(const struct St3Result *result,
                                             ArrowArrayStream *out_stream);

// Free a table handle previously returned by `st3_table_from_arrow`.
//
// A null pointer is a no-op.
//
// # Safety
// `handle` must be null or a pointer returned by `st3_table_from_arrow` that
// has not already been freed. Passing any other pointer, or freeing twice, is
// undefined behavior.
void st3_table_free(struct St3Table *handle);

// Free a result handle previously returned by `st3_run`.
//
// A null pointer is a no-op.
//
// # Safety
// `handle` must be null or a pointer returned by `st3_run` that has not already
// been freed. Passing any other pointer, or freeing twice, is undefined
// behavior.
void st3_result_free(struct St3Result *handle);

// Return the current thread's last-error message, or null if none is set.
//
// The pointer borrows a thread-local buffer owned by the library. It stays
// valid until the next SourceTracker3 call on the same thread; the caller must
// not free it or use it from another thread.
const char *st3_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ST3_H */
